import "./globals.css";
import { Ubuntu } from "next/font/google";

const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  style: ["italic", "normal"],
  display: "swap",
  fallback: ["system-ui", "arial", "verdana"]
});

export const metadata = {
  title: "Quick-R-Build",
  description:
    "Generated by create next app, a web app to help quickly make variants of a resume with a resume master.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  );
}
